name: http-cache-reqwest

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.ref }}-http-cache-reqwest
  cancel-in-progress: true

defaults:
 run:
  working-directory: ./http-cache-reqwest

jobs:
  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: "rustfmt"
      - run: cargo fmt -- --check

  test:
    name: Test stable on ${{ matrix.os }}
    needs: [fmt]
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          cargo test --all-targets --no-default-features --features reqwest-middleware,manager-cacache,manager-moka,manager-foyer,streaming,rate-limiting,http-headers-compat,url-standard
          cargo test --all-targets --no-default-features --features reqwest-middleware,manager-cacache,url-ada
          cargo test --lib --no-default-features --features middlewest,redirect,manager-cacache,streaming,rate-limiting,url-standard

  clippy:
    name: Check clippy
    needs: [fmt, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: "clippy"
      - run: |
          cargo clippy --lib --tests --all-targets --no-default-features --features reqwest-middleware,manager-cacache,manager-moka,manager-foyer,streaming,rate-limiting,http-headers-compat,url-standard -- -D warnings
          cargo clippy --lib --tests --all-targets --no-default-features --features reqwest-middleware,manager-cacache,url-ada -- -D warnings
          cargo clippy --lib --tests --no-default-features --features middlewest,redirect,manager-cacache,streaming,rate-limiting,url-standard -- -D warnings

  docs:
    name: Build docs
    needs: [fmt, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
        env:
          RUSTDOCFLAGS: --cfg docsrs -Dwarnings
      - run: |
          cargo doc --no-deps --document-private-items --no-default-features --features reqwest-middleware,manager-cacache,manager-moka,manager-foyer,manager-redb,streaming,rate-limiting,http-headers-compat,url-standard
          cargo test --doc --no-default-features --features reqwest-middleware,manager-cacache,manager-moka,manager-foyer,manager-redb,streaming,rate-limiting,http-headers-compat,url-standard
